In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv('IRIS.csv')
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [5]:
df['species'].replace({'Iris-setosa':1, 'Iris-versicolor':2, 'Iris-virginica':3},inplace=True)

In [6]:
df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        1
1             4.9          3.0           1.4          0.2        1
2             4.7          3.2           1.3          0.2        1
3             4.6          3.1           1.5          0.2        1
4             5.0          3.6           1.4          0.2        1
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        3
146           6.3          2.5           5.0          1.9        3
147           6.5          3.0           5.2          2.0        3
148           6.2          3.4           5.4          2.3        3
149           5.9          3.0           5.1          1.8        3

[150 rows x 5 columns]

In [7]:
x = df[['sepal_length','sepal_width', 'petal_length','petal_width']]

In [8]:
y = df['species']

In [9]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [10]:
y

0      1
1      1
2      1
3      1
4      1
      ..
145    3
146    3
147    3
148    3
149    3
Name: species, Length: 150, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [13]:
x_train

sepal_length  sepal_width  petal_length  petal_width
20            5.4          3.4           1.7          0.2
55            5.7          2.8           4.5          1.3
67            5.8          2.7           4.1          1.0
70            5.9          3.2           4.8          1.8
106           4.9          2.5           4.5          1.7
..            ...          ...           ...          ...
115           6.4          3.2           5.3          2.3
0             5.1          3.5           1.4          0.2
74            6.4          2.9           4.3          1.3
111           6.4          2.7           5.3          1.9
31            5.4          3.4           1.5          0.4

[105 rows x 4 columns]

In [14]:
x_test

sepal_length  sepal_width  petal_length  petal_width
45            4.8          3.0           1.4          0.3
17            5.1          3.5           1.4          0.3
65            6.7          3.1           4.4          1.4
16            5.4          3.9           1.3          0.4
89            5.5          2.5           4.0          1.3
51            6.4          3.2           4.5          1.5
47            4.6          3.2           1.4          0.2
63            6.1          2.9           4.7          1.4
66            5.6          3.0           4.5          1.5
25            5.0          3.0           1.6          0.2
97            6.2          2.9           4.3          1.3
143           6.8          3.2           5.9          2.3
33            5.5          4.2           1.4          0.2
68            6.2          2.2           4.5          1.5
77            6.7          3.0           5.0          1.7
131           7.9          3.8           6.4          2.0
149           5.9          3.0           5.1          1.8
37            4.9          3.1           1.5          0.1
24            4.8          3.4           1.9          0.2
3             4.6          3.1           1.5          0.2
93            5.0          2.3           3.3          1.0
101           5.8          2.7           5.1          1.9
10            5.4          3.7           1.5          0.2
6             4.6          3.4           1.4          0.3
100           6.3          3.3           6.0          2.5
23            5.1          3.3           1.7          0.5
4             5.0          3.6           1.4          0.2
88            5.6          3.0           4.1          1.3
7             5.0          3.4           1.5          0.2
135           7.7          3.0           6.1          2.3
87            6.3          2.3           4.4          1.3
83            6.0          2.7           5.1          1.6
8             4.4          2.9           1.4          0.2
119           6.0          2.2           5.0          1.5
44            5.1          3.8           1.9          0.4
144           6.7          3.3           5.7          2.5
84            5.4          3.0           4.5          1.5
43            5.0          3.5           1.6          0.6
91            6.1          3.0           4.6          1.4
39            5.1          3.4           1.5          0.2
128           6.4          2.8           5.6          2.1
13            4.3          3.0           1.1          0.1
122           7.7          2.8           6.7          2.0
11            4.8          3.4           1.6          0.2
145           6.7          3.0           5.2          2.3

In [15]:
y_train

20     1
55     2
67     2
70     2
106    3
      ..
115    3
0      1
74     2
111    3
31     1
Name: species, Length: 105, dtype: int64

In [16]:
y_test

45     1
17     1
65     2
16     1
89     2
51     2
47     1
63     2
66     2
25     1
97     2
143    3
33     1
68     2
77     2
131    3
149    3
37     1
24     1
3      1
93     2
101    3
10     1
6      1
100    3
23     1
4      1
88     2
7      1
135    3
87     2
83     2
8      1
119    3
44     1
144    3
84     2
43     1
91     2
39     1
128    3
13     1
122    3
11     1
145    3
Name: species, dtype: int64

In [17]:
len(x_train)

105

In [18]:
from sklearn.ensemble import RandomForestClassifier

In [19]:
 clf = RandomForestClassifier(n_estimators=100,criterion='gini') #n_estimator means how many trees added, ginni means impurity

In [20]:
clf.fit(x_train,y_train)

RandomForestClassifier()

In [21]:
clf.predict(x_test)

array([1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 3, 1, 2, 3, 3, 3, 1, 1, 1, 2, 3,
       1, 1, 3, 1, 1, 2, 1, 3, 2, 3, 1, 2, 1, 3, 2, 1, 2, 1, 3, 1, 3, 1,
       3], dtype=int64)

In [22]:
clf.score(x_test,y_test)

0.9333333333333333

In [23]:
from sklearn.metrics import r2_score,mean_squared_error

In [24]:
clf.predict([[3,4,2,1]])

C:\Users\Amol\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [25]:
clf.predict([[5,2,3,3]])

C:\Users\Amol\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([3], dtype=int64)

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
clf2 = DecisionTreeClassifier(criterion='gini',splitter='best')

In [28]:
clf2.fit(x_train,y_train)

DecisionTreeClassifier()

In [29]:
clf2.predict(x_test)

array([1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 3, 1, 2, 3, 3, 3, 1, 1, 1, 2, 3,
       1, 1, 3, 1, 1, 2, 1, 3, 2, 3, 1, 2, 1, 3, 2, 1, 2, 1, 3, 1, 3, 1,
       3], dtype=int64)

In [30]:
clf2.score(x_test,y_test)

0.9333333333333333

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
clf3 = LinearRegression()

In [33]:
clf3.fit(x_train,y_train)

LinearRegression()

In [34]:
clf3.predict(x_test)

array([1.04294452, 0.98681343, 2.18311182, 0.96815917, 2.21208194,
       2.3100847 , 1.00702968, 2.35154153, 2.43202323, 1.00390571,
       2.17562945, 3.08730694, 0.85087658, 2.36382565, 2.51790161,
       2.85710018, 2.72047406, 0.930558  , 1.09912599, 1.03472831,
       1.9325372 , 2.80272785, 0.90299765, 1.06241301, 3.30381982,
       1.18802007, 0.93871632, 2.21046207, 0.96886298, 3.01103142,
       2.20093793, 2.59262907, 1.0436344 , 2.51933925, 1.16600171,
       3.16954679, 2.46128385, 1.2327831 , 2.3238429 , 0.95423268,
       2.95930973, 0.91978549, 2.98659291, 1.0233742 , 2.93007913])

In [35]:
clf3.score(x_test,y_test)

0.9189817525148164

In [36]:
from sklearn.naive_bayes import GaussianNB

In [37]:
clf4 = GaussianNB()

In [38]:
clf4.fit(x_train,y_train)

GaussianNB()

In [39]:
clf4.predict(x_test)

array([1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 3, 1, 2, 3, 3, 3, 1, 1, 1, 2, 3,
       1, 1, 3, 1, 1, 2, 1, 3, 2, 3, 1, 2, 1, 3, 2, 1, 2, 1, 3, 1, 3, 1,
       3], dtype=int64)

In [40]:
clf4.score(x_test,y_test)

0.9333333333333333

In [41]:
from sklearn.svm import SVC

In [42]:
svc = SVC( kernel='linear')

In [43]:
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [44]:
svc.predict(x_test)

array([1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 3, 1, 2, 2, 3, 3, 1, 1, 1, 2, 3,
       1, 1, 3, 1, 1, 2, 1, 3, 2, 3, 1, 3, 1, 3, 2, 1, 2, 1, 3, 1, 3, 1,
       3], dtype=int64)

In [45]:
svc.score(x_test,y_test)

0.9777777777777777

In [46]:
svc = SVC(kernel='rbf')
svc.fit(x_train,y_train)

SVC()

In [47]:
import pickle
pickle.dump(svc,open('model.pkl','wb'))